name: flutter_movies_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
    sdk: ">=3.2.0 <4.0.0"

dependencies:
    flutter:
        sdk: flutter

    cupertino_icons: ^1.0.2
    freezed: ^2.4.6
    json_serializable: ^6.7.1
    freezed_annotation: ^2.4.1
    logger: ^2.0.2+1
    dio: ^5.4.0
    provider: ^6.1.1
    cached_network_image: ^3.3.1
    intl: ^0.19.0
    infinite_scroll_pagination: ^4.0.0
    sqflite: ^2.3.0
    path: ^1.8.3
    path_provider: ^2.1.1

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^2.0.0
    lints: ^2.1.1
    build_runner: ^2.4.7

flutter:
    uses-material-design: true
    assets: 
      - assets/config/
